import { WhatsAppConfig, DEFAULT_WHATSAPP_CONFIG } from "./contracts";

export interface SendWhatsAppResult {
  success: boolean;
  mode: "GATEWAY" | "WA_ME";
  messageId?: string;
  error?: string;
}

/**
 * Retrieves the currently saved WhatsApp configuration from localStorage,
 * falling back to clean defaults.
 */
export function getSavedWhatsAppConfig(): WhatsAppConfig {
  try {
    const saved = localStorage.getItem("dc_whatsapp_config");
    if (saved) {
      const parsed = JSON.parse(saved);
      // If user had previous default of localhost:3001 or empty, prefer Render Cloud
      return { ...DEFAULT_WHATSAPP_CONFIG, ...parsed };
    }
  } catch (e) {
    // fallback to default
  }
  return DEFAULT_WHATSAPP_CONFIG;
}

/**
 * Normalizes phone number into international E.164 format digits (defaulting to +91).
 */
export function normalizeWhatsAppNumber(rawPhone?: string, defaultPrefix = "91"): string {
  if (!rawPhone) return "";
  let digits = rawPhone.replace(/[^0-9]/g, "");
  if (!digits) return "";
  if (digits.length === 10) {
    digits = defaultPrefix.replace(/[^0-9]/g, "") + digits;
  }
  return digits;
}

export function formatWaPaisa(paisa: bigint): string {
  const isNeg = paisa < 0n;
  const abs = isNeg ? -paisa : paisa;
  const rupees = Number(abs / 100n);
  const remainder = Number(abs % 100n);
  const formatted = remainder > 0 ? `${rupees.toLocaleString("en-IN")}.${remainder.toString().padStart(2, "0")}` : `${rupees.toLocaleString("en-IN")}`;
  return `${isNeg ? "-" : ""}₹${formatted}`;
}

export interface DayCloseSummaryParams {
  shopName: string;
  date: string;
  time: string;
  operatorName?: string;
  physicalCountedPaisa: bigint;
  expectedCashPaisa: bigint;
  variancePaisa: bigint;
  todayCashInPaisa: bigint;
  todayCashOutPaisa: bigint;
  denominations: {
    n500: number;
    n200: number;
    n100: number;
    n50: number;
    n20: number;
    n10: number;
    coinsPaisa: bigint;
  };
  todaySalesCount?: number;
  todaySalesRevenuePaisa?: bigint;
  cspCommissionPaisa?: bigint;
  totalLiquidPoolsPaisa?: bigint;
  totalKhataDuePaisa?: bigint;
}

/**
 * Builds a structured, high-status Day-End (Z-Report) WhatsApp text message
 * suitable for business owners and executive night audits.
 */
export function buildDayCloseZReportWhatsAppText(params: DayCloseSummaryParams): string {
  const {
    shopName,
    date,
    time,
    operatorName,
    physicalCountedPaisa,
    expectedCashPaisa,
    variancePaisa,
    todayCashInPaisa,
    todayCashOutPaisa,
    denominations,
    todaySalesCount = 0,
    todaySalesRevenuePaisa = 0n,
    cspCommissionPaisa = 0n,
    totalLiquidPoolsPaisa = 0n,
    totalKhataDuePaisa = 0n,
  } = params;

  const isBalanced = variancePaisa === 0n;
  const varianceIcon = isBalanced ? "✅ EXACT BALANCED (₹0.00 Variance)" : variancePaisa > 0n ? `⚠️ OVERAGE (${formatWaPaisa(variancePaisa)})` : `🚨 SHORTAGE (${formatWaPaisa(variancePaisa)})`;

  return [
    `*🏛️ ${shopName.toUpperCase()} - EOD CLOSING Z-REPORT*`,
    `📅 *Date:* ${date}  |  ⏰ *Time:* ${time}`,
    operatorName ? `👤 *Shift In-Charge:* ${operatorName}` : "",
    `───────────────────────`,
    `*💵 CASH DRAWER RECONCILIATION:*`,
    `• Physical Counted: *${formatWaPaisa(physicalCountedPaisa)}*`,
    `• System ERP Expected: *${formatWaPaisa(expectedCashPaisa)}*`,
    `• Audit Status: *${varianceIcon}*`,
    `───────────────────────`,
    `*📊 CASH BOOK INFLOW / OUTFLOW:*`,
    `• Inflows Received: *+${formatWaPaisa(todayCashInPaisa)}*`,
    `• Outflows & Expenses: *-${formatWaPaisa(todayCashOutPaisa)}*`,
    `• Net Cash Delta: *${formatWaPaisa(todayCashInPaisa - todayCashOutPaisa)}*`,
    `───────────────────────`,
    `*💼 BUSINESS DAY-SUMMARY:*`,
    `• Counter Sales: *${todaySalesCount} Bills* (${formatWaPaisa(todaySalesRevenuePaisa)})`,
    cspCommissionPaisa > 0n ? `• Banking CSP Commission: *${formatWaPaisa(cspCommissionPaisa)}*` : "",
    totalKhataDuePaisa > 0n ? `• Customer Khata Due: *${formatWaPaisa(totalKhataDuePaisa)}*` : "",
    totalLiquidPoolsPaisa > 0n ? `• Total Net Liquid Reserves: *${formatWaPaisa(totalLiquidPoolsPaisa)}*` : "",
    `───────────────────────`,
    `*🪙 PHYSICAL DENOMINATION AUDIT:*`,
    `• ₹500 × ${denominations.n500} = ₹${(denominations.n500 * 500).toLocaleString("en-IN")}`,
    `• ₹200 × ${denominations.n200} = ₹${(denominations.n200 * 200).toLocaleString("en-IN")}`,
    `• ₹100 × ${denominations.n100} = ₹${(denominations.n100 * 100).toLocaleString("en-IN")}`,
    `• ₹50  × ${denominations.n50}  = ₹${(denominations.n50 * 50).toLocaleString("en-IN")}`,
    `• ₹20  × ${denominations.n20}  = ₹${(denominations.n20 * 20).toLocaleString("en-IN")}`,
    `• ₹10  × ${denominations.n10}  = ₹${(denominations.n10 * 10).toLocaleString("en-IN")}`,
    `• Loose Coins = ${formatWaPaisa(denominations.coinsPaisa)}`,
    `───────────────────────`,
    `_Generated by DigitalCafe ERP • 100% Conserved Double-Entry Engine_`,
  ]
    .filter(Boolean)
    .join("\n");
}

/**
 * Dispatches a WhatsApp message in 1 click:
 * 1. Checks configured gateway URL (or Render cloud default).
 * 2. Attempts background HTTP POST to `${gatewayUrl}/send-message` with a 5s timeout.
 * 3. If configured local gateway fails or is offline, tries Render Cloud gateway directly.
 * 4. If both are unreachable, seamlessly falls back to wa.me instant link window.
 */
export async function sendWhatsAppMessage(
  phone: string | undefined,
  messageText: string,
  onNotify?: (msg: string) => void
): Promise<SendWhatsAppResult> {
  const config = getSavedWhatsAppConfig();
  const cleanPhone = normalizeWhatsAppNumber(phone, config.defaultCountryCode);
  const primaryUrl = (config.gatewayUrl || "https://sccomm-whatsapp-gateway.onrender.com").replace(/\/+$/, "");
  const fallbackCloudUrl = "https://sccomm-whatsapp-gateway.onrender.com";

  // If phone is provided, attempt 1-click Gateway background dispatch
  if (cleanPhone) {
    // Helper to send to a specific gateway URL
    const tryGatewaySend = async (targetUrl: string, timeoutMs = 6000): Promise<any> => {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), timeoutMs);

      const res = await fetch(`${targetUrl}/send-message`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          ...(config.gatewayApiKey ? { "x-api-key": config.gatewayApiKey } : {}),
        },
        body: JSON.stringify({
          phone: cleanPhone,
          message: messageText,
        }),
        signal: controller.signal,
      });
      clearTimeout(timeoutId);

      if (res.ok) {
        return await res.json().catch(() => ({}));
      }
      return null;
    };

    // Attempt 1: Configured Primary Gateway
    try {
      const data = await tryGatewaySend(primaryUrl, 5000);
      if (data && data.success) {
        if (onNotify) {
          onNotify(`✓ WhatsApp delivered in 1-click via Gateway to +${cleanPhone}!`);
        }
        return { success: true, mode: "GATEWAY", messageId: data.messageId };
      }
    } catch (err: any) {
      console.warn(`[WhatsApp Dispatch] Primary gateway (${primaryUrl}) unavailable:`, err?.message);
    }

    // Attempt 2: Auto-try Render Cloud Gateway if primary was localhost or different
    if (primaryUrl !== fallbackCloudUrl) {
      try {
        const data = await tryGatewaySend(fallbackCloudUrl, 8000);
        if (data && data.success) {
          if (onNotify) {
            onNotify(`✓ WhatsApp delivered in 1-click via Render Cloud to +${cleanPhone}!`);
          }
          return { success: true, mode: "GATEWAY", messageId: data.messageId };
        }
      } catch (err: any) {
        console.warn(`[WhatsApp Dispatch] Fallback cloud gateway unavailable:`, err?.message);
      }
    }
  }

  // Fallback: wa.me instant direct dispatch
  const encodedText = encodeURIComponent(messageText);
  const targetUrl = cleanPhone
    ? `https://wa.me/${cleanPhone}?text=${encodedText}`
    : `https://wa.me/?text=${encodedText}`;

  if (typeof window !== "undefined") {
    window.open(targetUrl, "_blank", "noopener,noreferrer");
  }

  if (onNotify) {
    onNotify(cleanPhone ? `✓ WhatsApp ready for +${cleanPhone}!` : "✓ WhatsApp ready to share!");
  }

  return { success: true, mode: "WA_ME" };
}
